### PR TITLE
Parse content from XML header

### PR DESCRIPTION
**Pull request by berique**
Some RSS like "http://feeds.folha.uol.com.br/folha/colunas/futebolnarede/rss091.xml" don't have content-type in the HTTP header.
So, setting option **xmlHeader** to **true**, will get encoding from XML Header (i.e.: `<?xml version="1.0" encoding="ISO-8859-1"?>`) and translate to UTF-8 with `iconv-lite`.

### CODE REVIEW

**Comment by bobby-brennan** [comment]
Thanks for the contribution! A few notes:

* Looks like you need to re-run `WRITE_GOLDEN=true npm test` to get the tests to pass
* I'd rather not include `iconv-lite`, as it more than doubles the size of the browser distribution. I believe ISO-8859-1 can be handled by Buffer
 * Rather than having an `xmlHeader` option, I think it makes sense to always use the encoding specified in the XML header when it's available

**Comment by berique** [comment]
Thanks for the notes.
I think you're right, buffer makes the job. The problem with always use the XML encoding is when if the http header content-type is different... It could be possible?

Enviado do meu smartphone Samsung Galaxy.
-------- Mensagem original --------De: Bobby Brennan <notifications@github.com> Data: 12/04/18  13:54  (GMT-03:00) Para: bobby-brennan/rss-parser <rss-parser@noreply.github.com> Cc: Henrique Moreno <berique@gmail.com>, Author <author@noreply.github.com> Assunto: Re: [bobby-brennan/rss-parser] Parse content from XML header (#57) 
Thanks for the contribution! A few notes:

Looks like you need to re-run WRITE_GOLDEN=true npm test to get the tests to pass
I'd rather not include iconv-lite, as it more than doubles the size of the browser distribution. I believe ISO-8859-1 can be handled by Buffer
Rather than having an xmlHeader option, I think it makes sense to always use the encoding specified in the XML header when it's available


—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/bobby-brennan/rss-parser","title":"bobby-brennan/rss-parser","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/bobby-brennan/rss-parser"}},"updates":{"snippets":[{"icon":"PERSON","message":"@bobby-brennan in #57: Thanks for the contribution! A few notes:\r\n\r\n* Looks like you need to re-run `WRITE_GOLDEN=true npm test` to get the tests to pass\r\n* I'd rather not include `iconv-lite`, as it more than doubles the size of the browser distribution. I believe ISO-8859-1 can be handled by Buffer\r\n * Rather than having an `xmlHeader` option, I think it makes sense to always use the encoding specified in the XML header when it's available"}],"action":{"name":"View Pull Request","url":"https://github.com/bobby-brennan/rss-parser/pull/57#issuecomment-380873941"}}}

**Comment by bobby-brennan** [comment]
It's possible the HTTP encoding will be different from the XML encoding, but I think we should respect the XML encoding in that case, since it's closer to the encoded content.

**Comment by bobby-brennan** [comment]
Thought about this a bit. I think if the encodings are different, the XML is likely double-encoded. E.g. the XML body is encoded in latin1, and then the HTTP response is base64 encoded. In that case, we'd want to decode the HTTP response from base64, which would reveal the `<?xml version="1.0" encoding="ISO-8859-1"?>` header. Then we'd use that to decode the XML body from latin1.

Does that make sense?

**Comment by berique** [comment]
Yeah, it’s makes sense… I’m having issue with the decode, primarily from HTTP to the parse string function, even with Buffer.

**Comment by rbren** [comment]
This is pretty stale at this point - closing now, but feel free to reopen.

**Pull request closed without merging**
