### PR TITLE
Add requestOptions passthrough 

### LINKED ISSUE #137: Add options in parseURL such as rejectUnauthorized to bypass HTTPS issues.
Hi @rbren , thanks for this awesome library.
I would like to ask if it's ok to add options in the parseURL such as rejectUnauthorized to override some options there.

Screen Shot 2019-10-23 at 7 25 39 PM

I encountered an issue with some RSS with HTTPS saying "unable to verify the first certificate"
w/c was resolved by using adding NODE_TLS_REJECT_UNAUTHORIZED=0 in the .env, however it is not recommended and what they recommend is adding rejectUnauthorized in the get method (w/c i did in the code above)

Let me know your thought. 
I can also submit a PR if that's ok.
Thank you.

### PR DESCRIPTION
**Pull request by timqian**
Fix #137

Might also be useful in other situations

We can also use [@types/node](https://www.npmjs.com/package/@types/node) to validate the types, but I am not sure if you would like to add another dependency to this lib.

### CODE REVIEW

**Comment by rbren** [comment]
Thanks! Can you update `index.d.ts` with the new option? I think adding `@types/node` in there would be good too - I don't think it will increase the size of the browser-only distro.

**Comment by timqian** [comment]
@rbren The `RequestOptions` type is added, turns out the `@types/node` module is [installed by default](https://stackoverflow.com/a/44417509/4674834) so we don't need to add it again

**Comment by rbren** [comment]
Awesome, thanks!

**Comment by timqian** [comment]
@rbren 
Thanks for merging, when do you plan to push it to npm?

**Comment by rbren** [comment]
Oops, forgot :)

Published now as 3.8.0

**Pull request merged**
